export const TOGGLE_MUSIC_PLAYER = 'TOGGLE_MUSIC_PLAYER'
export const TOGGLE_ADD_FORM = 'TOGGLE_ADD_FORM'
export const TOGGLE_PLAYLIST_FORM = 'TOGGLE_PLAYLIST_FORM'
export const TOGGLE_MENU = 'TOGGLE_MENU'